### ISSUE TITLE
List of all pokemon [New Endpoint]

### ISSUE THREAD

**Issue by Shudy** [PokeDevs/pokedex-api#1]
#### I'm opening this issue because:

 -  [ ] I have a question/doubt.
 -  [ ] I want to report a bug/issue.
 -  [X] I want to request a feature or suggest something.
 -  [ ] Other: 

#### Description:

Taking a look to it, I saw we have the endpoint "pokemon/{id|name}", which returns the pokemon info.

But, there is no endpoint that list all the pokemon. Response can be a short array of a piece of info like:

```json
{
    "name": "<pokemon_name>",
    "id": "<pokemon_id>",
    "url": "<pokemon_url_info>"
}
```

With this type of endpoint we can have a list of all the pokemon, so in apps or webapps can be used to show the user all the existing pokemons, allowing the user to go to the specific info of it.

Thanks in advance

**Comment by paulomfr** [comment]
Someone news about this issue?

**Comment by matheusflauzino** [comment]
Someone news about this issue?

**Comment by iamtraction** [comment]
Yeah, I'll start working on it soon. Will also be adding the new gen 8 pokemon.

**Comment by iamtraction** [comment]
implemented in v2 https://github.com/PokeDevs/pokedex-api/issues/17
