### ISSUE TITLE
Update to Gen VIII

### ISSUE THREAD

**Issue by TinLeCS** [PokeDevs/pokedex-api#10]
#### I'm opening this issue because:

 -  [ ] I have a question/doubt.
 -  [ ] I want to report a bug/issue.
 -  [X] I want to request a feature or suggest something.
 -  [ ] Other: 

#### Description:

I really love this API because of its ease of use. Is there any by any change you will update it to Gen VIII. Is it possible for me contribute to it too?

**Comment by iamtraction** [comment]
> Is there any by any change you will update it to Gen VIII. 

Yeah, I use it myself so I'm planning to start on this soon.

> Is it possible for me contribute to it too?

If you can gather the data, in the same format, and send it to me I can implement it much faster.

**Comment by TinLeCS** [comment]
Sound good to me. I'm kinda busy at the moment but I can do some during weekends. Does json file work for you? And How can I send it to you? I'd also like to update description for Pokemon forms too as they have different flavor texts.

**Comment by iamtraction** [comment]
> Does json file work for you?

Yeah, that''d be just fine.

> And How can I send it to you?

Are you on Discord? If not, you can send it via some file sharing tool.
