### ISSUE TITLE
Wrong data for Mega Gyarados

### ISSUE THREAD

**Issue by TinLeCS** [PokeDevs/pokedex-api#11]
#### I'm opening this issue because:

 -  [ ] I have a question/doubt.
 -  [X] I want to report a bug/issue.
 -  [ ] I want to request a feature or suggest something.
 -  [ ] Other: 

#### Description:

Data returned from https://pokeapi.glitch.me/v1/pokemon/130 for Mega Gyarados is wrong
{
    "number": "131",
    "types": [
      "Water",
      "Flying"
    ],
    "sprite": "https://cdn.traction.one/pokedex/pokemon/131-mega.png",
    "description": "This gentle POKéMON loves to give people rides and provides a very comfortable way to get around."
}
It should be
{
    "number": "130",
    "types": [
      "Water",
      "Dark"
    ],
    "sprite": "https://cdn.traction.one/pokedex/pokemon/130-mega.png",
    "description": "Mega Evolution places a burden on its body. The stress causes it to become all the more ferocious."
}

**Comment by iamtraction** [comment]
Thanks, I'll fix it as soon as practical.

**Comment by u5ele55** [comment]
Any updates? This problem is still seems to exist

**Comment by iamtraction** [comment]
It has been fixed.

**Comment by u5ele55** [comment]
Mega Gyarados is Water & Dark type, and in this api it's still Water & Flying.

**Comment by iamtraction** [comment]
It should be fixed. Thanks for the report! Feel free to open another issue if you find more issues in the API.
