### ISSUE TITLE
API Calls Recently Began Returning 404's

### ISSUE THREAD

**Issue by ScriptingGuy24** [PokeDevs/pokedex-api#12]
#### I'm opening this issue because:

 -  [ ] I have a question/doubt.
 -  [x] I want to report a bug/issue.
 -  [ ] I want to request a feature or suggest something.
 -  [ ] Other: 

#### Description:
API calls for each and every Pokemon I try are resulting in a 404 error each time. Was working fine a few weeks ago.

I am still however able to access sprite images through editing this link for whichever pokemon is desired: **https://cdn.traction.one/pokedex/pokemon/149.png**

**Comment by iamtraction** [comment]
I'm able to get it. Could you try again and lemme know?

**Comment by ScriptingGuy24** [comment]
Hi Traction, it's working fine now. Thank you very much.
