### ISSUE TITLE
Add new Galar pokemons

### ISSUE THREAD

**Issue by malbouy** [PokeDevs/pokedex-api#13]
I was able to find that new galar pokemons (Generation VIII) are missing from the api and it would be great if you could add them as well! Thanks!

**Comment by sks316** [comment]
@iamtraction any update on this as well as the other issues that haven't been addressed? I'm also noticing that my issue, #3, is still valid and Meltan & Melmetal still aren't on the API. I also noticed #6 which is closed despite the Galar Pokemon not being on the API.
I'd love to help out if you need an extra set of hands on this.
