### ISSUE TITLE
How to use the gender attribute?

### ISSUE THREAD

**Issue by CavanhaMan** [PokeDevs/pokedex-api#14]
#### I'm opening this issue because:

 -  [x] I have a question/doubt.
 -  [ ] I want to report a bug/issue.
 -  [ ] I want to request a feature or suggest something.
 -  [ ] Other:

**Comment by CavanhaMan** [comment]
If I use:
data['0']['gender'] 
I get:
87.5,12.5
What does that mean?

**Comment by iamtraction** [comment]
it's the [gender ratio](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_gender_ratio) for the pokemon.
