### ISSUE TITLE
Image Problems

### ISSUE THREAD

**Issue by lmarcosss** [PokeDevs/pokedex-api#15]
#### I'm opening this issue because:

 -  [ ] I have a question/doubt.
 -  [X] I want to report a bug/issue.
 -  [ ] I want to request a feature or suggest something.
 -  [ ] Other: 

#### Description:

The pokemon images, doesn't work, i don't know if has a problem to the api but this url doesn't work [example image](https://cdn.traction.one/pokedex/pokemon/4.png)

**Comment by iamtraction** [comment]
It should now be working.
