### ISSUE TITLE
API Endpoint for Fetching Pokémon Data Returns HTML Instead of JSON

### ISSUE THREAD

**Issue by ffrank89** [PokeDevs/pokedex-api#18]
#### I'm opening this issue because:
 -  [ ] I have a question/doubt.
 -  [ X] I want to report a bug/issue.
 -  [ ] I want to request a feature or suggest something.
 -  [ ] Other: 

#### Description:
When attempting to fetch Pokémon data from the https://ex.traction.one/pokedex/pokemon/{pokemon_name} endpoint, the expected JSON response is not returned. Instead, an HTML document is received, which seems to be a generic template or a placeholder, indicating the request might not be reaching a live API service. I could not find anything about HTML responses in the readme so I am led to believe this is an error.

#### Steps to Reproduce:

1. Execute a curl command to the endpoint

`curl -i -X GET \
  -H "User-Agent: BastionDiscordBot (https://bastion.traction.one, v10.13.0)" \
  https://ex.traction.one/pokedex/pokemon/greninja`
  
  or just 
`curl https://ex.traction.one/pokedex/pokemon/greninja`

2. See that the response is a generic HTML response rather than JSON with expected Pokemon data

#### Additional Information
1. This issue was encountered when working on a Spring Boot application that uses this API. Requests made in this application specified the content header as "application/json"

**Comment by iamtraction** [comment]
Try running your code again. It should work now, if it still doesn't work, try clearing your DNS cache and it should work.
