### ISSUE TITLE
[Feature Request] Type effectiveness

### ISSUE THREAD

**Issue by ruchernchong** [PokeDevs/pokedex-api#2]
#### I'm opening this issue because:

 -  [ ] I have a question/doubt.
 -  [ ] I want to report a bug/issue.
 -  [X] I want to request a feature or suggest something.
 -  [ ] Other: 

#### Description:
The current API only has the type of Pokemon. It will be great if the API contains properties like `effective`, `resistance` as an array.

e.g. Using Pikachu

```
{
  "effective": ["water", "flying"],
  "resistance": ["ground"]
}
```

**Comment by iamtraction** [comment]
This is a great suggestion. But currently I don't have enough time to collect the required data for it and implement it, so it might take some time for this to be implemented.

Although, if you want to contribute feel free to do hop into [our Discord server](https://discord.gg/7P4H3TY) and we can talk what can be done.

**Comment by ruchernchong** [comment]
Don't worry. Take your time, just a suggestion anyway, I have no rush for this.

**Comment by lyzerglick** [comment]
I created a python script that takes in two lists of pokemon and calculates overall effectiveness between the teams based on their type attributes. It is probably not well optimized by any means but I could provide it to anyone as a starting point to automatically tag pokemon with properties for their effectiveness.

If anyone is interested  let me know and I can put the code on github. The most helpful part might be a handcoded nested dictionary of all types matched with each other and the respective effectivness to emulate the classic "type effectiveness table" charts.

**Comment by ruchernchong** [comment]
Since this seemed to have become stale, I will be closing this for now.
