### ISSUE TITLE
Meltan and Melmetal aren't on the API

### ISSUE THREAD

**Issue by sks316** [PokeDevs/pokedex-api#3]
#### I'm opening this issue because:

 -  [ ] I have a question/doubt.
 -  [X] I want to report a bug/issue.
 -  [ ] I want to request a feature or suggest something.
 -  [ ] Other: 

#### Description:

I found your API recently, and I'd just like to note that [Meltan](https://bulbapedia.bulbagarden.net/wiki/Meltan_(Pokémon)) and [Melmetal](https://bulbapedia.bulbagarden.net/wiki/Melmetal_(Pokémon)) don't seem to be on the API. This is obviously a big problem.

**Comment by sks316** [comment]
Adding onto this, [Gourgeist](https://bulbapedia.bulbagarden.net/wiki/Gourgeist_(Pokémon))'s name seems to be incorrect - It is incorrectly labeled "Pumpkaboo".

**Comment by iamtraction** [comment]
808 & 809 were relatively recently added. I'll add them to the API soon.

**Comment by iamtraction** [comment]
Closing this as they have been added.
