### ISSUE TITLE
Add sprites for Primals

### ISSUE THREAD

**Issue by ilhamwahabi** [PokeDevs/pokedex-api#4]
#### I'm opening this issue because:

 -  [ ] I have a question/doubt.
 -  [x] I want to report a bug/issue.
 -  [ ] I want to request a feature or suggest something.
 -  [ ] Other: 

#### Description:

Primal Kyogre sprite still directed to https://pokeres.bastionbot.org/images/pokemon/382.png and Primal Groudon sprite still directed to https://pokeres.bastionbot.org/images/pokemon/383.png

**Comment by iamtraction** [comment]
That's because Primal revisions haven't been added to the API yet. Will add them as soon as I get time for this. Thank you.

**Comment by ilhamwahabi** [comment]
Any update on this?

**Comment by iamtraction** [comment]
Ah, completely forgot about this. Will add it by the end of this weekend.

**Comment by ilhamwahabi** [comment]
Thanks, can't wait!

**Comment by iamtraction** [comment]
Sprites for Primal forms are now available. The data returned by the API now points to the proper sprite.

**Comment by ilhamwahabi** [comment]
Is this already deployed? Seems primal forms sprite still not the right one

https://pokeapi.glitch.me/v1/pokemon/382
https://pokeapi.glitch.me/v1/pokemon/383

**Comment by iamtraction** [comment]
Yeah, it's deployed already. Probably it was returning the cached response. I checked just now, it's returning the correct one.
