### ISSUE TITLE
The API is gone?

### ISSUE THREAD

**Issue by sks316** [PokeDevs/pokedex-api#5]
#### I'm opening this issue because:

 -  [ ] I have a question/doubt.
 -  [X] I want to report a bug/issue.
 -  [ ] I want to request a feature or suggest something.
 -  [ ] Other: 

#### Description:

Title is self-explanatory. The API stopped working today, and accessing it through a browser shows a Glitch 404 page saying the project can't be found.

**Comment by iamtraction** [comment]
It was down for some time. It's up and running now.
