### ISSUE TITLE
Error 1011 Access denied for showing image

### ISSUE THREAD

**Issue by ilhamwahabi** [PokeDevs/pokedex-api#7]
#### I'm opening this issue because:

 -  [ ] I have a question/doubt.
 -  [X] I want to report a bug/issue.
 -  [ ] I want to request a feature or suggest something.
 -  [ ] Other: 

#### Description:

Got error when accessing image, or any change how we should use image now?

![error](https://i.imgur.com/yXVeIBd.png)

**Comment by iamtraction** [comment]
Are you still facing this issue?

**Comment by ilhamwahabi** [comment]
Thanks! It's solved now
