### ISSUE TITLE
Pokemon API calls no longer working - CORS?

### ISSUE THREAD

**Issue by mabdulul** [PokeDevs/pokedex-api#9]
Access to fetch at 'https://pokeapi.glitch.me/v1/pokemon/716' from origin 'http://localhost:5000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

#### I'm opening this issue because:

 -  [ ] I have a question/doubt.
 -  [x] I want to report a bug/issue.
 -  [ ] I want to request a feature or suggest something.
 -  [ ] Other:

**Comment by iamtraction** [comment]
Yeah, this is intentional. You can't directly access the API using browser's Fetch API. You need to make requests from a backend server. Read the docs and make use of one of the provided libraries, or make your own.
